# Generated by Django 3.1.2 on 2020-10-27 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveys',
            options={'permissions': (('can_edit_survey', 'Edit Survey'),)},
        ),
        migrations.RenameField(
            model_name='surveys',
            old_name='survey_taker',
            new_name='surveyer',
        ),
    ]
