# Generated by Django 3.1.2 on 2020-11-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201104_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
